import styled, { keyframes } from "styled-components";

const spinAnimation = keyframes`
  0% { transform: translate(-50%, -50%) rotate(0deg); }
  100% { transform: translate(-50%, -50%) rotate(360deg); }
`;

const SpinnerContainer = styled.div`
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
`;

const SpinnerInner = styled.div`
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
`;

const SpinnerElement = styled.div`
  position: absolute;
  width: 70px;
  height: 70px;
  border: 10px solid #59e63d;
  border-top-color: transparent;
  border-radius: 50%;
  animation: ${spinAnimation} 1s linear infinite;
  top: 100px;
  left: 100px;
`;

const Spinner = () => {
  return (
    <SpinnerContainer>
      <SpinnerInner>
        <SpinnerElement />
      </SpinnerInner>
    </SpinnerContainer>
  );
};

export default Spinner;

{
  /* <div class="loadingio-spinner-rolling-paujs0o2oat"><div class="ldio-i3zugrg1zmk">
<div></div>
</div></div>
<style type="text/css">
@keyframes ldio-i3zugrg1zmk {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-i3zugrg1zmk div {
  position: absolute;
  width: 120px;
  height: 120px;
  border: 20px solid #59e63d;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-i3zugrg1zmk div {
  animation: ldio-i3zugrg1zmk 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-paujs0o2oat {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-i3zugrg1zmk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
// .ldio-i3zugrg1zmk div { box-sizing: content-box; }
/* generated by https://loading.io/ */
// </style> */}
